Repository JuliaLang/Pkg.jl, pull requests merged in 2018-09, with the labels that each got.

#680 work around strange "Unreachable reached" when the close function for a repo fires when updating registries
  src/API.jl
Labels: backport pending 1.0

#721 Close the braces in docstring
  src/Pkg.jl
Labels: backport pending 1.0, docs

#715 Fix the statements for checking repeat in packages' UUID.
  src/Types.jl
Labels: backport pending 1.0, bugfix

#712 Expand ~ in path for activate develop and add
  src/REPLMode.jl
  src/Types.jl
  test/repl.jl
Labels: enhancement

#724 Don't mutate argument passed to Pkg.add
  src/API.jl
  test/pkg.jl
Labels: backport pending 1.0, bugfix

#747 Fix spelling of "precompile"
  src/API.jl
Labels: backport pending 1.0

#752 fix type in isjoinable
  src/versions.jl
  test/pkg.jl
Labels: backport pending 1.0

#716 Update project.toml compat example
  docs/src/index.md
Labels: backport pending 1.0, docs

#756 only look up name from url if it is unset
  src/Types.jl
Labels: backport pending 1.0, bugfix

#753 mention what package failed to install
  .travis.yml
Labels: backport pending 1.0

#742 Reword `activate` docs
  src/Pkg.jl
Labels: backport pending 1.0

#735 only do a radiomenu if we are in interactive mode
  src/Types.jl
Labels: backport pending 1.0, bugfix

#734 do not precompile packages that have opt out to precompilation
  src/API.jl
Labels: backport pending 1.0
