Repository JuliaLang/Pkg.jl, pull requests merged in 2018-08, with the labels that each got.

#572 Also collect manifest entries from target deps when testing / building.
  src/Operations.jl
  test/pkg.jl
  test/test_packages/x1/Project.toml
  test/test_packages/x1/src/x1.jl
  test/test_packages/x2/Project.toml
  test/test_packages/x2/src/x2.jl
  test/test_packages/x3/Project.toml
  test/test_packages/x3/src/x3.jl
  test/test_packages/x3/test/runtests.jl
Labels: bugfix

#632 add bors file
  bors.toml
Labels: backport pending 1.0

#631 stop testing on 0.7
  .travis.yml
  appveyor.yml
Labels: backport pending 1.0

#637 Enable CI on bors branches.
  .travis.yml
  appveyor.yml
Labels: backport pending 1.0

#643 stop testing on 32 bit
  appveyor.yml
Labels: backport pending 1.0

#599 Remove `--env` meta option
  src/REPLMode.jl
  test/repl.jl
Labels: backport pending 1.0

#618 better info messages for activating new env
  src/API.jl
  test/repl.jl
Labels: backport pending 1.0

#646 remove unnecessary version handling when dealing with repos
  src/Operations.jl
  src/Types.jl
Labels: backport pending 1.0, bugfix

#648 Remove precompile things from repo
  src/Pkg.jl
  src/precompile.jl
Labels: backport pending 1.0

#594 add path completions to add/dev in repl
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, needs changelog

#649 update the repo when the gitobject is not available
  src/Types.jl
  test/pkg.jl
  test/repl.jl
  test/utils.jl
Labels: backport pending 1.0, bugfix, needs changelog

#657 Fix a bug where the path was stored as relative
  src/API.jl
  src/Operations.jl
  src/Types.jl
  test/repl.jl
Labels: backport pending 1.0, bugfix

#603 Fix `preview` and update completions
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, backport pending 1.0, needs changelog

#674 update AppVeyor URL
  README.md
Labels: backport pending 1.0

#676 Update Pkg docs to reflect version change to v1.0
  docs/src/index.md
Labels: backport pending 1.0
