Repository JuliaLang/Pkg.jl, pull requests merged in 2018-10, with the labels that each got.

#773 WIP(ish): Real documentation.
  docs/make.jl
  docs/src/api.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/faq.md
  docs/src/getting-started.md
  docs/src/glossary.md
  docs/src/index.md
  docs/src/managing-packages.md
  docs/src/registries.md
Labels: docs

#794 fix so we are not counting symlinks size as the linked file size
  src/API.jl
Labels: backport pending 1.0, bugfix

#791 respect color option in REPL
  src/REPLMode.jl
Labels: backport pending 1.0, bugfix

#802 fix path completions
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, backport pending 1.0, bugfix

#720 Allow trailing backslash in regex
  src/Types.jl
Labels: backport pending 1.0

#807 Fix Pkg.test docstring
  src/Pkg.jl
Labels: backport pending 1.0, docs

#818 Refactor command declarations
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, refactoring

#748 Add a message for empty project deps
  src/Display.jl
Labels: backport pending 1.0

#725 Cleanup most temporary dirs, fix #704, fix #723.
  src/Operations.jl
  src/Types.jl
  test/api.jl
  test/pkg.jl
  test/repl.jl
  test/utils.jl
Labels: backport pending 1.0

#844 Fix bootstrapping Pkg.
  src/REPLMode.jl
Labels: backport pending 1.0

#848 Expand symlinks in find_project_file.
  src/Types.jl
  test/pkg.jl
Labels: REPL, backport pending 1.0

#850 Clarify tilde specifications in documentation, fix #847.
  docs/src/compatibility.md
Labels: backport pending 1.0, docs

#733 only update registries in first depot path
  src/API.jl
Labels: backport pending 1.0, bugfix, registries

#839 Refactor completions
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, refactoring
