Repository JuliaLang/Pkg.jl, pull requests merged in 2018-07, with the labels that each got.

#469 also add recursive dependencies to the package being tested/built
  src/Operations.jl
  test/repl.jl
  test/test_packages/BigProject/Manifest.toml
  test/test_packages/BigProject/Project.toml
  test/test_packages/BigProject/RecursiveDep/Project.toml
  test/test_packages/BigProject/RecursiveDep/src/RecursiveDep.jl
  test/test_packages/BigProject/RecursiveDep2/Project.toml
  test/test_packages/BigProject/RecursiveDep2/src/RecursiveDep2.jl
  test/test_packages/BigProject/SubModule/Project.toml
  test/test_packages/BigProject/SubModule/src/SubModule.jl
Labels: bugfix

#495 only set the pkg.repo.rev in case of upgrading
  docs/src/index.md
  src/Types.jl
  test/repl.jl
Labels: bugfix

#497 put target deps inside deps of package when running the target
  src/Operations.jl
Labels: bugfix

#514 do not throw when failing to fetch a registry
  src/API.jl
Labels: bugfix

#523 fix gc
  src/API.jl
Labels: bugfix

#517 Rework the meaning of `pkg> activate Foo`
  src/REPLMode.jl
  test/repl.jl
Labels: enhancement

#534 Docs and some API usabilities
  docs/make.jl
  docs/src/index.md
  src/API.jl
  src/Pkg.jl
  src/REPLMode.jl
  src/Types.jl
  test/pkg.jl
Labels: docs

#548 fix unneeded use of pwd in REPL prompt function
  src/REPLMode.jl
  test/repl.jl
Labels: bugfix
