Repository JuliaLang/Pkg.jl, pull requests merged in 2018-11, with the labels that each got.

#869 Add completion support for `activate`
  src/REPLMode.jl
  test/repl.jl
Labels: REPL

#588 Registry functionality with REPL and API support
  .gitignore
  CHANGELOG.md
  docs/src/api.md
  docs/src/registries.md
  src/API.jl
  src/GitTools.jl
  src/Pkg.jl
  src/REPLMode.jl
  src/Registry.jl
  src/Types.jl
  test/pkg.jl
  test/registry.jl
  test/repl.jl
  test/runtests.jl
  test/utils.jl
Labels: REPL, registries

#884 fix #711: multiple registries with the same package
  src/Types.jl
  test/registry.jl
Labels: backport pending 1.0, bugfix

#886 Disable startup.jl in BigProject tests, fix #815.
  test/test_packages/BigProject/test/runtests.jl
Labels: backport pending 1.0, test

#881 pkg> status SomePackage
  CHANGELOG.md
  src/API.jl
  src/Display.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode.jl
  test/api.jl
  test/repl.jl
Labels: REPL, enhancement

#898 typo in PackageSpec docstring
  src/Pkg.jl
Labels: backport pending 1.0, docs

#897 Use permutedims instead of LinearAlgebra.transpose (via Base), fix #896.
  src/GraphType.jl
Labels: backport pending 1.0

#905 Define read_project for IO types, fix #904.
  src/Types.jl
  test/repl.jl
Labels: bugfix

#916 Print the normalized url.
  src/GitTools.jl
Labels: backport pending 1.0, display and printing

#917 Add cut_body_after to bors.toml.
  bors.toml
Labels: ci

#921 fix #913: only remove the path if it was a temp-path.
  src/Types.jl
  test/pkg.jl
Labels: backport pending 1.0, bugfix

#925 Fix tab completion and toml reading
  src/REPLMode.jl
  src/Types.jl
  test/manifest/bad/missing_entry.toml
  test/manifest/bad/parse_error.toml
  test/manifest/good/not_unique_names.toml
  test/manifest/good/simple.toml
  test/pkg.jl
  test/project/bad/parse_error.toml
  test/project/good/pkg.toml
  test/project/good/simple.toml
Labels: bugfix

#937 Fix RegistrySpec docstring
  src/Pkg.jl
Labels: docs
