Repository JuliaLang/Pkg.jl, pull requests merged in 2019-05, with the labels that each got.

#1197 Consistent spacing for REPL mode help.
  src/REPL/command_declarations.jl
Labels: display and printing

#1199 Wrap reading of project status in HEAD in try-catch, fixes #1180.
  src/Display.jl
  test/pkg.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, bugfix

#1200 Fix st -m X when X is in manifest but not in project, fixes #1183.
  src/API.jl
  test/api.jl
Labels: backport pending 1.1, backport pending 1.2, bugfix

#1203 Safer Project.toml and Manifest.toml printing
  src/manifest.jl
  src/project.jl
Labels: backport pending 1.2, bugfix

#1207 Make sure we have found the registry path when developing
  src/Types.jl
  test/api.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, bugfix

#1210 `up` should load complete manifest info
  src/Operations.jl
  test/pkg.jl
Labels: backport pending 1.2, bugfix
