Repository JuliaLang/Pkg.jl, pull requests merged in 2019-11, with the labels that each got.

#1489 do not throw errors when autocompleting
  src/REPLMode/completions.jl
  test/repl.jl
Labels: REPL, bugfix

#1499 Document IO redirection
  docs/src/api.md
Labels: documentation

#1485 Relocatable `@artifact_str`
  src/Artifacts.jl
Labels: artifacts, backport pending 1.3

#1504 (Updated) Remove OS-specific shell commands from Pkg docs
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/getting-started.md
  docs/src/managing-packages.md
  docs/src/registries.md
Labels: documentation

#1410 Allow hyphenated ranges in compatability specs
  docs/src/compatibility.md
  src/versions.jl
  test/pkg.jl
Labels: enhancement

#1513 fix GitTools.tree_hash executableness criterion
  src/GitTools.jl
  test/artifacts.jl
  test/new.jl
Labels: backport pending 1.3
