Repository JuliaLang/Pkg.jl, pull requests merged in 2019-02, with the labels that each got.

#1041 Display diff when `path` changes
  src/Display.jl
Labels: display and printing

#1049 Display status for the correct environment when testing.
  src/Operations.jl
Labels: bugfix, display and printing, sandbox

#1054 Set version to 1.0.4.
  Project.toml
Labels: release

#1056 fix absolutifying path when looking for deps
  src/Operations.jl
Labels: bugfix

#1058 fix "locking" dependencies when building / testing current project
  src/backwards_compatible_isolation.jl
  test/pkg.jl
  test/test_packages/BuildProjectFixedDeps/.gitignore
  test/test_packages/BuildProjectFixedDeps/Manifest.toml
  test/test_packages/BuildProjectFixedDeps/Project.toml
  test/test_packages/BuildProjectFixedDeps/deps/build.jl
  test/test_packages/BuildProjectFixedDeps/src/BuildProjectFixedDeps.jl
Labels: backport pending 1.0, backport pending 1.1

#1061 Pkg.add should return nothing.
  src/API.jl
  test/api.jl
Labels: API, bugfix

#1074 Document new test/Project.toml setup, fixes #1031.
  docs/src/creating-packages.md
Labels: docs, sandbox

#1075 Fix compat: `julia` is an implicit dependency
  src/project.jl
Labels: Input Validation, bugfix

#1078 fix undefvar when reporting error for version 0.0.0
  src/versions.jl
Labels: bugfix

#1068 Update doc strings for pin, free
  src/Pkg.jl
Labels: docs

#1080 Overload Base.showerror instead of Base.show for PkgError.
  src/Types.jl
  test/pkg.jl
Labels: display and printing

#1079 fix #1077: handle stdlibs in update_package_add and friends
  src/Operations.jl
  test/pkg.jl
Labels: bugfix

#1093 Make sandbox isolation more flexible
  src/Operations.jl
  test/sandbox.jl
  test/test_packages/Sandbox_PreserveTestDeps/Manifest.toml
  test/test_packages/Sandbox_PreserveTestDeps/Project.toml
  test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/Project.toml
  test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/src/Foo.jl
  test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/Manifest.toml
  test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/Project.toml
  test/test_packages/Sandbox_PreserveTestDeps/dev/Foo/test/runtests.jl
  test/test_packages/Sandbox_PreserveTestDeps/src/Sandbox_PreserveTestDeps.jl
Labels: sandbox
