Repository JuliaLang/Pkg.jl, pull requests merged in 2019-04, with the labels that each got.

#1148 Fix outdated develop docstring, fixes #1082.
  src/REPL/command_declarations.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, docs

#1151 Update Documenter to version 0.22.X.
  docs/Project.toml
  docs/make.jl
Labels: docs

#1154 Fix bug in dependency graph creation
  src/GraphType.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2

#1164 Fix printing when installing from git.
  src/Operations.jl
  src/backwards_compatible_isolation.jl
Labels: backport pending 1.2, display and printing

#1166 Use printpkgstyle for activate.
  src/API.jl
  test/repl.jl
Labels: backport pending 1.2, display and printing

#1171 few minor doc improvements
  README.md
  docs/src/api.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/getting-started.md
  docs/src/glossary.md
  docs/src/managing-packages.md
  docs/src/registries.md
  docs/src/toml-files.md
  src/Pkg.jl
  src/REPL/command_declarations.jl
Labels: backport pending 1.2, docs

#1173 generate: use uuid4() instead of uuid1()
  src/generate.jl
Labels: backport pending 1.2

#1175 Added registering packages section
  docs/src/creating-packages.md
Labels: backport pending 1.2, docs
