Repository JuliaLang/Pkg.jl, pull requests merged in 2019-12, with the labels that each got.

#1529 clarify: stacked envs only affect top-level loading
  docs/src/index.md
Labels: documentation

#1534 Bug fix: Make sure sandbox's temp Project.toml and Manifest.toml files are writable
  src/Operations.jl
Labels: backport pending 1.3, bugfix

#1537 PlatformEngines: use `tar -m` to ignore mtimes
  src/PlatformEngines.jl
Labels: backport pending 1.3

#1488 Introduce special REPL syntax for shared environments
  src/REPLMode/REPLMode.jl
  src/REPLMode/argument_parsers.jl
  src/REPLMode/command_declarations.jl
  src/REPLMode/completions.jl
  test/new.jl
Labels: REPL, enhancement

#1540 Adjust GC delay and add `--all` flag to circumvent delay
  src/API.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/command_declarations.jl
  test/new.jl
Labels: enhancement

#1549 provide a fallback when sandboxing a package with no Project.toml
  src/Operations.jl
  test/new.jl
Labels: backport pending 1.3

#1559 remove some unnecessary struct fields
  src/API.jl
  src/Display.jl
  src/Operations.jl
  src/REPLMode/completions.jl
  src/Types.jl
  test/pkg.jl
Labels: Refactoring

#1562 Update doc string for #1540
  src/API.jl
Labels: documentation

#1563 test: `Pkg.test` on dependencies with same name but different UUID
  test/new.jl
  test/test_packages/SameNameDifferentUUID/Manifest.toml
  test/test_packages/SameNameDifferentUUID/Project.toml
  test/test_packages/SameNameDifferentUUID/dev/Example/Project.toml
  test/test_packages/SameNameDifferentUUID/dev/Example/src/Example.jl
  test/test_packages/SameNameDifferentUUID/dev/Example/test/runtests.jl
  test/test_packages/SameNameDifferentUUID/dev/Unregistered/Project.toml
  test/test_packages/SameNameDifferentUUID/dev/Unregistered/README.md
  test/test_packages/SameNameDifferentUUID/dev/Unregistered/src/Unregistered.jl
  test/test_packages/SameNameDifferentUUID/src/SameNameDifferentUUID.jl
Labels: testing
