Repository JuliaLang/Pkg.jl, pull requests merged in 2019-06, with the labels that each got.

#1209 Check for consistent toml files before `instantiate`ing
  src/API.jl
  test/pkg.jl
  test/test_packages/ExtraDirectDep/Manifest.toml
  test/test_packages/ExtraDirectDep/Project.toml
Labels: backport pending 1.2, bugfix

#1222 Don't put recursive dependencies in the test/build project, fixes #1144.
  src/backwards_compatible_isolation.jl
  test/test_packages/BuildProjectFixedDeps/deps/build.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, bugfix

#1224 Make note about gen_project a note.
  docs/src/creating-packages.md
Labels: backport pending 1.2, docs

#1229 Fix gc when unexpected files are located in package directories
  src/API.jl
  test/pkg.jl
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, bugfix

#1237 Add tilde examples using a major version of 0
  docs/src/compatibility.md
Labels: backport pending 1.2
