Repository JuliaLang/Pkg.jl, pull requests merged in 2019-07, with the labels that each got.

#1242 Add notes about interaction between Project.toml, test/Project.toml
  docs/src/creating-packages.md
Labels: backport pending 1.2, docs, sandbox

#1226 [RFC] Allow Pkg.test to pass command-line arguments to test/runtests.jl
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/backwards_compatible_isolation.jl
  test/api.jl
  test/test_packages/TestArguments/Project.toml
  test/test_packages/TestArguments/src/TestArguments.jl
  test/test_packages/TestArguments/test/runtests.jl
Labels: triage

#1270 Fix error message when adding a package with the same name or UUID as project
  src/API.jl
Labels: backport pending 1.2
