Repository JuliaLang/Pkg.jl, pull requests merged in 2019-09, with the labels that each got.

#1340 Slightly tweak computation of manifest file name in case no (Julia)Manifest.toml exist.
  src/Types.jl
Labels: backport pending 1.3

#1335 Set quiet_download to true by default.
  src/PlatformEngines.jl
Labels: artifacts, backport pending 1.3

#1344 Give a proper error for registered_name(...) = nothing
  src/Operations.jl
Labels: backport pending 1.0, backport pending 1.2, backport pending 1.3

#1339 Fully support JuliaArtifacts.toml filename everywhere.
  docs/src/artifacts.md
  src/Artifacts.jl
  src/Operations.jl
  test/artifacts.jl
Labels: artifacts, backport pending 1.3

#1333 More printing updates
  src/API.jl
  src/Operations.jl
  src/Registry.jl
  src/Types.jl
  src/backwards_compatible_isolation.jl
  src/generate.jl
Labels: display and printing

#1347 Update Documenter to 0.23, fix doctests.
  docs/Project.toml
  docs/make.jl
Labels: backport pending 1.3, docs

#1325 More informative error messages when parsing manifest files.
  src/manifest.jl
  test/manifest/bad/bad_dep_name.toml
Labels: error handling

#1215 Highlight a bit more the posibility of relative paths
  docs/src/managing-packages.md
Labels: docs

#1351 Simplify REPLMode by removing `CommandKind`
  src/REPL/command_declarations.jl
  src/REPL/completions.jl
  src/REPLMode.jl
  test/repl.jl
Labels: REPL, refactoring

#1350 Fix `compress_versions()` confusion with build number VersionNumber's
  src/versions.jl
  test/pkg.jl
Labels: backport pending 1.3

#1353 Properly Plumb Platform kwarg for `ensure_artifact_installed()`
  src/Artifacts.jl
  test/artifacts.jl
Labels: backport pending 1.3

#1360 Add a note about PkgTemplates
  docs/src/creating-packages.md
Labels: docs

#1369 Update link to gen_project.jl script.
  docs/src/creating-packages.md
Labels: backport pending 1.3, docs

#1368 fix tab completion error with invalid arguments
  src/REPLMode/completions.jl
  test/repl.jl
Labels: REPL, bugfix

#1363 Verify that content of unpacked tarball matches git-tree-sha1.
  src/Operations.jl
Labels: security

#1330 Introduce support for tiered resolver
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/command_declarations.jl
  src/Types.jl
  test/api.jl
  test/test_packages/ShouldPreserveAll/Manifest.toml
  test/test_packages/ShouldPreserveAll/Project.toml
  test/test_packages/ShouldPreserveDirect/Manifest.toml
  test/test_packages/ShouldPreserveDirect/Project.toml
  test/test_packages/ShouldPreserveNone/Manifest.toml
  test/test_packages/ShouldPreserveNone/Project.toml
  test/test_packages/ShouldPreserveSemver/Manifest.toml
  test/test_packages/ShouldPreserveSemver/Project.toml
  test/utils.jl
Labels: Type: Enhancement, resolver

#1354 Offload `PackageSpec` checking from REPL to API layer
  src/API.jl
  src/REPLMode/argument_parsers.jl
  src/REPLMode/command_declarations.jl
  test/repl.jl
Labels: REPL, Type: Enhancement, error handling

#1365 fix "double expanding" homedir on tab complete
  src/REPLMode/completions.jl
  test/repl.jl
Labels: REPL, Type: Bug

#1364 add support for instantiating lonely manifest
  src/API.jl
  src/Pkg.jl
  test/manifest/noproject/Manifest.toml
  test/pkg.jl
  test/utils.jl
Labels: Enhancement

#1370 also check that name is resolved
  src/Types.jl
  test/pkg.jl
Labels: Bug

#1381 small refactor of write_env functions
  src/Display.jl
  src/Operations.jl
  src/Types.jl
  src/backwards_compatible_isolation.jl
  src/manifest.jl
  src/project.jl
Labels: Refactoring

#1383 Fix broken link to `gen_project.jl`
  docs/src/creating-packages.md
Labels: Documentation

#1392 Add EditURL to basedocs.md
  docs/src/basedocs.md
Labels: Documentation, backport pending 1.3

#1379 Describe pre-1.0 behavior in the compat section
  docs/src/compatibility.md
Labels: Documentation, backport pending 1.3

#1394 Make files read only more often
  src/Operations.jl
  src/Types.jl
Labels: backport pending 1.2, backport pending 1.3, bugfix

#1389 make sure to return project after testing artifact
  test/artifacts.jl
Labels: testing

#1374 Fix `instantiate` not installing artifacts
  src/API.jl
  src/Artifacts.jl
  src/Operations.jl
  src/PlatformEngines.jl
  test/artifacts.jl
Labels: Bug, artifacts, backport pending 1.3

#1400 Enable Travis and Appveyor
  .travis.yml
  appveyor.yml
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, backport pending 1.3

#1406 Run CI for release-* branches, remove staging.
  .travis.yml
  appveyor.yml
Labels: backport pending 1.0, backport pending 1.1, backport pending 1.2, backport pending 1.3, ci

#1408 `rm` should always preserve `julia` compat
  src/Operations.jl
  test/api.jl
  test/test_packages/BasicCompat/Project.toml
Labels: backport pending 1.1, backport pending 1.2, backport pending 1.3

#1409 Better cleanup of temporary files in install_archive.
  src/Operations.jl
Labels: backport pending 1.3, enhancement

#1412 Silence verbose `7z` output, fixes #1376.
  src/PlatformEngines.jl
Labels: backport pending 1.3

#1361 [release-1.3] Backports for 1.3.0
  .travis.yml
  appveyor.yml
  docs/src/basedocs.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  src/API.jl
  src/Artifacts.jl
  src/Operations.jl
  src/PlatformEngines.jl
  src/Types.jl
  src/versions.jl
  test/api.jl
  test/artifacts.jl
  test/pkg.jl
  test/test_packages/BasicCompat/Project.toml
Labels: Backports, release

#1385 Refactoring to get rid of some old stuff and move some types into better place
  bin/recompress.jl
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/argument_parsers.jl
  src/Resolve/Resolve.jl
  src/Resolve/graphtype.jl
  src/Types.jl
  src/backwards_compatible_isolation.jl
  src/utils.jl
  test/api.jl
  test/pkg.jl
  test/registry.jl
  test/resolve.jl
Labels: Refactoring

#1372 Rework repo handling
  docs/src/managing-packages.md
  src/API.jl
  src/Display.jl
  src/GitTools.jl
  src/Operations.jl
  src/REPLMode/argument_parsers.jl
  src/Types.jl
  src/backwards_compatible_isolation.jl
  src/manifest.jl
  test/api.jl
  test/pkg.jl
  test/repl.jl
  test/utils.jl
Labels: enhancement

#1399 Implement undo and redo functionality
  docs/src/api.md
  src/API.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/command_declarations.jl
  src/Types.jl
  src/manifest.jl
  src/project.jl
  test/pkg.jl
Labels: Feature

#1420 Clarify backward-compatible feature additions require only minor bump in pre-1.0 packages
  docs/src/compatibility.md
  docs/src/toml-files.md
Labels: Documentation

#1419 WIP: refactor some of the repo handling code
  src/API.jl
  src/GitTools.jl
  src/Operations.jl
  src/Types.jl
  test/utils.jl
Labels: Refactoring

#1414 properly return to the previous project in with_envs
  test/utils.jl
Labels: Tests

#1384 Refactor tests
  src/API.jl
  src/GitTools.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/argument_parsers.jl
  src/REPLMode/command_declarations.jl
  src/Registry.jl
  src/Types.jl
  test/api.jl
  test/new.jl
  test/pkg.jl
  test/repl.jl
  test/runtests.jl
  test/test_packages/EmptyPackage/Project.toml
  test/test_packages/EmptyPackage/src/EmptyPackage.jl
  test/test_packages/Example/Project.toml
  test/test_packages/Example/src/Example.jl
  test/test_packages/SimplePackage/Project.toml
  test/test_packages/SimplePackage/Project2.toml
  test/test_packages/SimplePackage/src/SimplePackage.jl
  test/test_packages/TestTarget/Project.toml
  test/utils.jl
Labels: testing
