Repository JuliaLang/Pkg.jl, pull requests merged in 2019-10, with the labels that each got.

#1437 Change direct path to `7z` to point toward `libexec`, not `bin`
  src/PlatformEngines.jl
Labels: backport pending 1.3, priority

#1438 Call expanduser in pkg> generate, fixes #1435.
  src/REPLMode/command_declarations.jl
  src/generate.jl
  test/new.jl
Labels: backport pending 1.3

#1442 Look in `bin` for `7z` for in-tree builds
  src/PlatformEngines.jl
Labels: backport pending 1.3, priority

#1479 Add compat annotations for Artifacts API, fixes #1476.
  docs/src/artifacts.md
  src/Artifacts.jl
Labels: artifacts, backport pending 1.3, documentation
