Repository JuliaLang/Pkg.jl, pull requests merged in 2020-06, with the labels that each got.

#1848 improve precompile execution
  src/Pkg.jl
Labels: backport pending 1.5

#1862 Fix bug which made `registry up` a no-op
  src/Registry.jl
Labels: backport pending 1.4, backport pending 1.5

#1871 telemetry: print legal notice first time talking to each pkg server
  src/Pkg.jl
  src/PlatformEngines.jl
Labels: backport pending 1.5

#1881 telemetry: use RandomDevice for random values
  src/PlatformEngines.jl
Labels: backport pending 1.5

#1883 Disable SIGQUIT test that regularly segfaults on CI.
  test/pkg.jl
Labels: backport pending 1.5

#1884 A few fixes
  src/API.jl
  src/Operations.jl
  test/manifest/unpruned/Manifest.toml
  test/manifest/unpruned/Project.toml
  test/new.jl
Labels: backport pending 1.5

#1885 Make tree hash computation non-fatal when installing artifacts.
  src/Artifacts.jl
  test/artifacts.jl
Labels: artifacts, backport pending 1.4, backport pending 1.5
