Repository JuliaLang/Pkg.jl, pull requests merged in 2020-01, with the labels that each got.

#1577 Fix the help message of the build command
  src/REPLMode/command_declarations.jl
Labels: documentation

#1580 Properly `esc()` variable in `@artifact_str`
  src/Artifacts.jl
  test/test_packages/ArtifactInstallation/src/ArtifactInstallation.jl
Labels: backport pending 1.3, backport pending 1.4

#1576 [WIP] fix `fixed` option for `Pkg.update`
  src/Operations.jl
  test/new.jl
Labels: backport pending 1.4, bugfix

#1582 remove @show debug output when test fails
  src/Operations.jl
Labels: backport pending 1.4

#1581 Include directories that contain only symlinks to other directories
  src/GitTools.jl
  test/new.jl
Labels: backport pending 1.3, backport pending 1.4

#1567 BinaryPlatforms: Add `armv6l` architecture
  src/BinaryPlatforms.jl
  test/binaryplatforms.jl
Labels: backport pending 1.3, backport pending 1.4

#1591 fix bind_artifact! docstring for download_info
  src/Artifacts.jl
Labels: backport pending 1.4

#1595 use expanduser instead of replace with homedir()
  src/REPLMode/argument_parsers.jl
Labels: backport pending 1.4

#1592 Adjust `Pkg.test` printing
  src/API.jl
  src/Operations.jl
Labels: backport pending 1.4

#1599 Update precompile script to block cloning of registry
  src/Pkg.jl
Labels: backport pending 1.4

#1603 require handling
  src/Operations.jl
  test/new.jl
Labels: backport pending 1.4

#1611 Some more compat with 1.3
  src/Operations.jl
  src/Pkg.jl
  src/Types.jl
Labels: backport pending 1.4

#1615 use quiet_download when stderr is not a TTY
  src/Artifacts.jl
Labels: backport pending 1.4

#1619 fix precompile script
  src/Pkg.jl
Labels: backport pending 1.4

#1620 make artifact download more similar to rest of Pkg "theme"
  src/Artifacts.jl
  src/Operations.jl
  src/PlatformEngines.jl
  src/Types.jl
Labels: backport pending 1.4

#1623 Misc doc changes
  .travis.yml
  docs/Project.toml
  docs/make.jl
  docs/src/compatibility.md
  docs/src/managing-packages.md
  docs/src/toml-files.md
  src/BinaryPlatforms.jl
Labels: backport pending 1.3, backport pending 1.4

#1626 make telemetry file writing more likely to be atomic
  src/PlatformEngines.jl
Labels: backport pending 1.4

#1635 relax project file validation
  src/Types.jl
  test/new.jl
Labels: backport pending 1.4

#1627 tweak the code for getting the registry from PkgServer
  src/Types.jl
Labels: backport pending 1.4, package-servers

#1617 Fix `gen_unpack_cmd()` signature inconsistency
  src/PlatformEngines.jl
Labels: backport pending 1.4

#1639 remove the cache for devved packages
  src/Types.jl
Labels: backport pending 1.4, bugfix

#1637 fix path resolution bug introduced in #1372
  src/REPLMode/argument_parsers.jl
  src/utils.jl
  test/new.jl
Labels: backport pending 1.4

#1641 fix not trying to delete moved file in load_telemetry_file
  src/PlatformEngines.jl
Labels: backport pending 1.4
