Repository JuliaLang/Pkg.jl, pull requests merged in 2020-02, with the labels that each got.

#1669 fix error message for probing
  src/PlatformEngines.jl
Labels: backport pending 1.4

#1671 Allow pkg server in scheme://netloc/path format
  src/Pkg.jl
  src/PlatformEngines.jl
  test/platformengines.jl
Labels: backport pending 1.4

#1686 write_env_usage: use proper TOML writer (fix #1681)
  src/Types.jl
Labels: backport pending 1.0, backport pending 1.4

#1690 fix bug in Operations.source_path with paths relative to project
  src/API.jl
  src/Operations.jl
  src/Types.jl
  test/new.jl
Labels: backport pending 1.4

#1693 Pkg telemetry headers: GITHUB_ACTION => GITHUB_ACTIONS
  src/PlatformEngines.jl
Labels: backport pending 1.4

#1696 Add current project as a Fixed package for the resolver and fix a bug when developed packages had cycles in paths
  src/Operations.jl
  test/new.jl
  test/pkg.jl
  test/test_packages/ExtraDirectDep/src/ExtraDirectDep.jl
Labels: bugfix
