Repository JuliaLang/Pkg.jl, pull requests merged in 2020-08, with the labels that each got.

#1932 Better error message from Pkg.pin when package is not found in the manifest.
  src/Operations.jl
Labels: backport pending 1.5, error handling

#1959 try instantiate without updating the registry
  src/API.jl
Labels: backport pending 1.5

#1957 some microoptimizations for the resolver
  src/Resolve/Resolve.jl
  src/Resolve/fieldvalues.jl
  src/Resolve/graphtype.jl
  src/Resolve/maxsum.jl
  src/Resolve/versionweights.jl
  src/Types.jl
Labels: performance

#1960 Fix an invalidation from overloading `broadcasted`
  src/PlatformEngines.jl
Labels: backport pending 1.5

#1953 Propagate Threads.nthreads() to Pkg.test subprocess.
  src/Operations.jl
Labels: backport pending 1.5

#1972 Fix a few more inference issues
  ext/TOML/src/print.jl
  src/Artifacts.jl
  src/BinaryPlatforms.jl
  src/PlatformEngines.jl
  src/REPLMode/REPLMode.jl
  src/Types.jl
  src/utils.jl
Labels: latency

#1970 Adopt consistent Float64 in auth expiration time
  src/PlatformEngines.jl
Labels: latency

#1958 add project to manifest in case a package depends on it, so that manifest is always complete
  src/Operations.jl
  test/new.jl
Labels: backport pending 1.5, bugfix

#1971 Avoid unnecessary eltype promotion of various array containers
  src/PlatformEngines.jl
  src/REPLMode/command_declarations.jl
  src/Resolve/graphtype.jl
  src/versions.jl
Labels: latency

#1969 Redesign the HashType handling for better inference
  src/GitTools.jl
  test/new.jl
Labels: latency

#1968 Improve consistency of Dict types & construction
  src/API.jl
  src/Artifacts.jl
  src/BinaryPlatforms.jl
  src/Operations.jl
  src/REPLMode/REPLMode.jl
  src/Resolve/graphtype.jl
  src/Types.jl
  test/artifacts.jl
  test/binaryplatforms.jl
  test/pkg.jl
  test/repl.jl
  test/resolve_utils.jl
Labels: latency

#1936 REPL: Fix parsing git URLs
  src/REPLMode/argument_parsers.jl
  test/repl.jl
Labels: backport pending 1.5

#1981 Correctly pass on the ctx::Context when adding default registries.
  src/Types.jl
Labels: backport pending 1.5

#1979 Pkg.gc: only print active manifests/artifacts in verbose mode.
  src/API.jl
  src/REPLMode/command_declarations.jl
Labels: display and printing

#1988 fix typo
  src/API.jl
Labels: backport pending 1.5

#1992 Fix a typo in error message: malfomed -> malformed.
  src/project.jl
Labels: backport pending 1.5
