Repository JuliaLang/Pkg.jl, pull requests merged in 2020-04, with the labels that each got.

#1751 improve performance of TOML parsing by reading from memory instead of from file
  ext/TOML/src/TOML.jl
  src/Operations.jl
  src/Types.jl
  src/manifest.jl
Labels: TOML, performance

#1422 add subdir functionality
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/Types.jl
  src/manifest.jl
  test/pkg.jl
  test/test_packages/MainRepo/SubDir/Project.toml
  test/test_packages/MainRepo/SubDir/src/SubDir.jl
Labels: feature

#1772 Correctly set the uuid for default registries
  src/Types.jl
Labels: backport pending 1.4

#1777 Download source files before parsing artifact files, fixes #1775.
  src/API.jl
Labels: artifacts, backport pending 1.4, bugfix, needs test
