Repository JuliaLang/Pkg.jl, pull requests merged in 2020-05, with the labels that each got.

#1358 Add a more concise way to call the API functions
  src/API.jl
  src/Pkg.jl
  test/new.jl
  test/pkg.jl
Labels: API, enhancement

#1265 Offline mode
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/completions.jl
  src/Types.jl
  test/new.jl
Labels: API, feature

#1809 Add [offline] to prompt in offline mode
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.5

#1819 REPL: make SPECS a normal variable
  src/REPLMode/REPLMode.jl
  src/REPLMode/completions.jl
Labels: backport pending 1.4

#1776 [WIP] backports release 1.4
  ext/TOML/src/TOML.jl
  ext/TOML/src/parser.jl
  ext/TOML/src/print.jl
  src/API.jl
  src/GitTools.jl
  src/Operations.jl
  src/Pkg.jl
  src/PlatformEngines.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/completions.jl
  src/Types.jl
  src/manifest.jl
  test/artifacts.jl
  test/new.jl
  test/pkg.jl
  test/subdir 2.jl
  test/test_packages/ExtraDirectDep/src/ExtraDirectDep 2.jl
  test/test_packages/MainRepo/SubDir/Project 2.toml
  test/test_packages/MainRepo/SubDir/src/SubDir 2.jl
  test/test_packages/Status/Manifest 2.toml
  test/test_packages/Status/Project 2.toml
  test/test_packages/TestSubgraphTrackingPath/Manifest.toml
  test/test_packages/TestSubgraphTrackingPath/Project.toml
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/Manifest.toml
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/Project.toml
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/dev/Example/Project.toml
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/dev/Example/src/Example.jl
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/dev/Example/test/runtests.jl
  test/test_packages/TestSubgraphTrackingPath/dev/Unregistered/src/Unregistered.jl
  test/test_packages/TestSubgraphTrackingPath/src/TestSubgraphTrackingPath.jl
  test/test_packages/TestSubgraphTrackingPath/test/Manifest.toml
  test/test_packages/TestSubgraphTrackingPath/test/Project.toml
  test/test_packages/TestSubgraphTrackingPath/test/runtests.jl
Labels: release

#1824 Improve inference of call chains to TOML.print
  ext/TOML/src/parser.jl
  ext/TOML/src/print.jl
  src/Artifacts.jl
  src/PlatformEngines.jl
Labels: backport pending 1.5

#1827 Fix ~/nested/path expansion
  src/REPLMode/completions.jl
  test/repl.jl
Labels: needs test

#1841 some perf improvements
  src/Operations.jl
  src/versions.jl
Labels: backport pending 1.5
