Repository JuliaLang/Pkg.jl, pull requests merged in 2021-10, with the labels that each got.

#2749 Fix resolver's bug #2740
  src/Resolve/Resolve.jl
  test/resolve.jl
Labels: resolver, backport pending 1.7

#2812 [CI] For now, disable the "Check Historical Stdlib Generator" CI check
  .github/workflows/check_hsg.yml
Labels: continuous integration (CI)

#2809 Delete the `test/testgroups` file
  test/testgroups
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2808 If `Base.DEPOT_PATH` is empty, `Pkg.PlatformEngines.get_server_dir` should return `nothing` (instead of erroring)
  src/PlatformEngines.jl
Labels: continuous integration (CI), bugfix, backport pending 1.6, backport pending 1.7

#2805 Pkg test suite: change an `old_depot_path = DEPOT_PATH` to `old_depot_path = copy(DEPOT_PATH)`
  test/artifacts.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2804 Pkg test suite: during the `subdir functionality` tests, use the correct absolute path when loading the `MainRepo` test package
  test/pkg.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2803 Pkg test suite: do not try to write to or modify the directory containing the Pkg source code
  test/runtests.jl
  test/utils.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7
