Repository JuliaLang/Pkg.jl, pull requests merged in 2021-11, with the labels that each got.

#2737 [release-1.6] Try to improve the error message in one of the possible "manifest mismatch" code paths
  src/Operations.jl
Labels: error handling

#2814 CI: deduplicate some code (i.e. always use the `.ci/test_and_change_uuid.jl` script, for consistency)
  .github/workflows/test.yml
Labels: continuous integration (CI)

#2818 Pkg test suite: in the `TestArguments` test package, relax the assertion that `Base.JLOptions().depwarn` is `1`
  test/test_packages/TestArguments/test/runtests.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2820 [CI] Actually use the correct arch when downloading Julia, and update one of the tests to use Permutations v0.4.9
  .github/workflows/test.yml
  test/new.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2816 Precompile: don't instantiate again after an instantiate
  src/API.jl
  src/Pkg.jl
Labels: backport pending 1.6, backport pending 1.7

#2824 More forcefully encourage `ArtifactOverrideLoading` to recompile when loaded the second time
  test/artifacts.jl
Labels: continuous integration (CI), backport pending 1.6, backport pending 1.7

#2828 Add `upgrade_manifest(manifest_path::String)` for updating explicit manifests
  src/API.jl
  src/Pkg.jl
  test/manifests.jl
Labels: backport pending 1.6

#2827 Cache pkg_server_registry_info
  src/Operations.jl
  src/Registry/Registry.jl
Labels: registries, backport pending 1.6, backport pending 1.7

#2826 Fix Project equality when compat entries are present
  src/Types.jl
  test/new.jl
  test/project/good/withcompat.toml
Labels: backport pending 1.6, backport pending 1.7

#2834 prevent internet access during precompile script
  src/Pkg.jl
Labels: backport pending 1.7

#2830 Improve error handling when registry downloads fail
  src/Registry/Registry.jl
Labels: registries, backport pending 1.7

#2862 Add default registry if none available during pkg install prompt
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.7
