Repository JuliaLang/Pkg.jl, pull requests merged in 2021-02, with the labels that each got.

#2382 Fix p7zip usage on alpine
  Project.toml
  src/PlatformEngines.jl
Labels: backport pending 1.6

#2377 If the `JULIA_PKG_SERVER` environment variable is not set, use Git for cloning registries
  src/Registry/Registry.jl
Labels: backport pending 1.5, backport pending 1.6, package-servers, registries

#2389 Run GitHub Action on master and release branches
  .github/workflows/test.yml
  README.md
Labels: continuous integration (CI)

#2391 Make downloads respect IO
  src/API.jl
  src/Artifacts.jl
  src/Operations.jl
  src/PlatformEngines.jl
  src/Registry/Registry.jl
  test/new.jl
Labels: backport pending 1.6
