Repository JuliaLang/Pkg.jl, pull requests merged in 2021-08, with the labels that each got.

#2699 Fix a couple of invalidations from extending ==
  ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl
  src/Operations.jl
Labels: latency

#2284 wip: --outdated flag to status
  CHANGELOG.md
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/command_declarations.jl
  test/new.jl
Labels: display and printing

#2715 Improve the local optimizer at the end of resolve
  src/Resolve/Resolve.jl
  src/Resolve/graphtype.jl
  test/resolve.jl
  test/resolve_utils.jl
  test/resolvedata2.jl
Labels: backport pending 1.6, backport pending 1.7
