Repository JuliaLang/Pkg.jl, pull requests merged in 2021-05, with the labels that each got.

#2543 Use the current std(out|err) for printing, fixes #2542.
  src/API.jl
  src/Artifacts.jl
  src/Operations.jl
  src/Pkg.jl
  src/PlatformEngines.jl
  src/Registry/Registry.jl
  src/Types.jl
  test/resolve.jl
Labels: backport pending 1.6

#2558 Docstrings: add references from `Pkg.add` to `Pkg.develop` and vice versa
  src/Pkg.jl
Labels: documentation

#2559 If the user tries to `Pkg.add(; path = ...)` a path that is not a Git repo, suggest `Pkg.develop` instead
  src/Types.jl
  test/pkg.jl
Labels: error handling

#2563 Test suite: replace one use of `first(...)` with `only(...)`
  test/new.jl
Labels: test

#2579 Precompile: Improve handling of packages that are missing modules
  src/API.jl
Labels: backport pending 1.6
