Repository JuliaLang/Pkg.jl, pull requests merged in 2021-12, with the labels that each got.

#2870 Pkg.generate should use stderr.
  src/generate.jl
Labels: backport pending 1.7

#2884 Tweak missing registry package warning message
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.7

#2845 CI: Re-enable the "Check Historical Stdlib" CI check
  .github/workflows/check_hsg.yml
Labels: CI

#2871 Improve messaging in --all noops
  src/API.jl
  test/new.jl
Labels: backport pending 1.7

#2897 Don't return "julia" as an available missing package
  src/REPLMode/REPLMode.jl
  test/repl.jl
Labels: backport pending 1.7

#2858 Consistently parse all boolean environment variables
  src/Artifacts.jl
  src/GitTools.jl
  src/Pkg.jl
  src/Registry/Registry.jl
  src/utils.jl
Labels: backport pending 1.6, backport pending 1.7

#2898 Add the no-argument `Pkg.Registry.add()` method, which automatically installs the default registries
  src/Registry/Registry.jl
Labels: bugfix, backport pending 1.6, backport pending 1.7

#2900 Correct compat annotation for extended platform selection
  docs/src/artifacts.md
Labels: documentation, artifacts, backport pending 1.7

#2890 Expand manifest warning message
  src/manifest.jl
Labels: backport pending 1.7
