Repository JuliaLang/Pkg.jl, pull requests merged in 2021-03, with the labels that each got.

#2416 Fix Markdown table formatting
  src/Pkg.jl
Labels: backport pending 1.6

#2414 only use the stdlib version cache if a custom version is given to the resolver
  src/Types.jl
Labels: backport pending 1.6

#2426 Precomp: safer recall_precompile_state
  src/API.jl
Labels: backport pending 1.6

#2440 Update links in the manual to point to pkgdocs.julialang.org
  docs/src/basedocs.md
Labels: documentation

#2037 Clarify activate command signatures
  src/REPLMode/command_declarations.jl
Labels: documentation

#2457 Precompilation: Tidy report at end
  src/API.jl
Labels: backport pending 1.6

#2466 (revive) add pinning commit message
  docs/src/managing-packages.md
Labels: documentation

#2467 (revive) document that dev --local path is not supported
  src/REPLMode/command_declarations.jl
Labels: documentation

#2439 Add the `force_latest_compatible_version` keyword argument to `Pkg.test`
  .github/workflows/test.yml
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  test/force_latest_compatible_version.jl
  test/pkg_uuid.jl
  test/runtests.jl
  test/test_packages/force_latest_compatible_version/BothOldAndNew/.gitignore
  test/test_packages/force_latest_compatible_version/BothOldAndNew/Project.toml
  test/test_packages/force_latest_compatible_version/BothOldAndNew/src/BothOldAndNew.jl
  test/test_packages/force_latest_compatible_version/BothOldAndNew/test/runtests.jl
  test/test_packages/force_latest_compatible_version/DirectDepWithoutCompatEntry/.gitignore
  test/test_packages/force_latest_compatible_version/DirectDepWithoutCompatEntry/Project.toml
  test/test_packages/force_latest_compatible_version/DirectDepWithoutCompatEntry/src/DirectDepWithoutCompatEntry.jl
  test/test_packages/force_latest_compatible_version/DirectDepWithoutCompatEntry/test/runtests.jl
  test/test_packages/force_latest_compatible_version/NewOnly/.gitignore
  test/test_packages/force_latest_compatible_version/NewOnly/Project.toml
  test/test_packages/force_latest_compatible_version/NewOnly/src/NewOnly.jl
  test/test_packages/force_latest_compatible_version/NewOnly/test/runtests.jl
  test/test_packages/force_latest_compatible_version/OldOnly1/.gitignore
  test/test_packages/force_latest_compatible_version/OldOnly1/Project.toml
  test/test_packages/force_latest_compatible_version/OldOnly1/src/OldOnly1.jl
  test/test_packages/force_latest_compatible_version/OldOnly1/test/runtests.jl
  test/test_packages/force_latest_compatible_version/OldOnly2/.gitignore
  test/test_packages/force_latest_compatible_version/OldOnly2/Project.toml
  test/test_packages/force_latest_compatible_version/OldOnly2/src/OldOnly2.jl
  test/test_packages/force_latest_compatible_version/OldOnly2/test/runtests.jl
  test/utils.jl
Labels: API, feature

#2474 docs: tiny typo (missing endquote)
  src/Pkg.jl
Labels: documentation
