Repository JuliaLang/Pkg.jl, pull requests merged in 2021-06, with the labels that each got.

#2593 Add tests for #2589 (test that `Pkg.PackageSpec` accepts `Union{UUID, AbstractString, Nothing}` for `uuid`)
  test/api.jl
Labels: test

#2595 CI: Use the same alternate UUID every time
  .ci/change_uuid.jl
  .ci/test_and_change_uuid.jl
  .ci/test_uuid_is_unchanged.jl
  .github/workflows/test.yml
Labels: continuous integration (CI)

#2597 README: remind users to change the UUID back to the original UUID before they commit and push
  README.md
Labels: documentation

#2561 New Manifest.toml format: Pt 1. Teach Pkg new format, but default to old format
  src/Operations.jl
  src/Types.jl
  src/manifest.jl
  test/manifest/formats/v1.0/Manifest.toml
  test/manifest/formats/v1.0/Project.toml
  test/manifest/formats/v2.0/Manifest.toml
  test/manifest/formats/v2.0/Project.toml
  test/manifest/formats/v3.0_unknown/Manifest.toml
  test/manifest/formats/v3.0_unknown/Project.toml
  test/manifests.jl
  test/new.jl
  test/runtests.jl
  test/test_packages/BuildProjectFixedDeps/deps/build.jl
Labels: backport pending 1.6

#2580 New Manifest.toml format: Pt 2. Default to new format, warn if old format is being maintained
  src/API.jl
  src/Pkg.jl
  src/Types.jl
  src/manifest.jl
  test/manifests.jl
Labels: merge me

#2603 Remove unnecessary manifest lookup in `apply_force_latest_compatible_version!`
  src/Operations.jl
Labels: bugfix

#2610 New manifest format: Fix `upgrade_manifest` and raw dict entry for nothing
  src/manifest.jl
  test/manifests.jl
Labels: backport pending 1.7, bugfix

#2612 New Manifest.toml format: Don't write julia_version to manifest if nothing
  src/manifest.jl
Labels: backport pending 1.7

#2617 Automatically upgrade the sandbox manifest format when preserving
  src/Operations.jl
Labels: backport pending 1.7

#2622 fix not warning about old manifest during Pkg.test
  src/Operations.jl
Labels: backport pending 1.7

#2614 Enable installation of versioned historical stdlibs
  src/Operations.jl
  src/Types.jl
  test/new.jl
  test/resolve.jl
Labels: backport pending 1.7

#2620 New manifest: Set `julia_version` during resolve only, and warn if instantiating a manifest that was resolved in a different or unknown julia version
  src/API.jl
  src/Operations.jl
  src/Types.jl
  src/manifest.jl
  test/manifests.jl
  test/new.jl
  test/repl.jl
Labels: backport pending 1.6, backport pending 1.7

#2625 `Pkg.build`: Don't build and precompile an uninstantiated environment twice
  src/API.jl
  src/Operations.jl
Labels: backport pending 1.6, backport pending 1.7, bugfix

#2631 Cancel pkg install prompt when ^D is entered
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.7, merge me

#2632 Cancel pkg install prompt when ^D is entered - Add a missing newline
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.7, merge me

#2634 CI: set a max timeout of 60 minutes
  .github/workflows/test.yml
Labels: merge me

#2651 When deciding whether to set an undo point, ignore manifest metadata
  src/API.jl
Labels: backport pending 1.6, backport pending 1.7

#2628 Backports for 1.6, take 2.
  src/API.jl
  src/Operations.jl
  src/Types.jl
  src/manifest.jl
Labels: release

#2654 Only run gc on the user-depot unless force=true, fixes #2642.
  src/API.jl
Labels: backport pending 1.7, bugfix
