Repository JuliaLang/Pkg.jl, pull requests merged in 2021-07, with the labels that each got.

#2658 Delete the `Pkg.Versions.:≳` function
  src/Versions.jl
Labels: merge me

#2660 During instantiate don't update the registry if there are no env deps
  src/API.jl
Labels: backport pending 1.6, backport pending 1.7

#2661 Make `write_env_usage` atomic
  src/Types.jl
Labels: backport pending 1.6, backport pending 1.7

#2675 Missing package install prompt: Strip any rogue spaces from user input
  src/REPLMode/REPLMode.jl
Labels: backport pending 1.7
