Repository JuliaLang/Pkg.jl, pull requests merged in 2022-09, with the labels that each got.

#3191 Test suite: restore the original depot path and load path at the end of the test suite
  test/runtests.jl
Labels: test, CI, backport 1.8

#3193 Test suite: skip the "ensure registry is installed" step if `Pkg.Registry.reachable_registries()` is not empty
  test/pkg.jl
Labels: test, CI

#3192 Test suite: restore the original `ENV` at the end of the test suite
  test/runtests.jl
Labels: test, CI

#3200 improve type stability of `Command(statement::Statement)`
  src/REPLMode/REPLMode.jl
Labels: latency, backport 1.8

#3202 improve inferrability of `prune_graph!`
  src/Resolve/graphtype.jl
Labels: latency, backport 1.8

#3158 remove unnecessary anonymous function in internals
  src/API.jl
Labels: Refactoring

#3136 Organize imports in Artifacts
  src/Artifacts.jl
Labels: Refactoring, merge me
