Repository JuliaLang/Pkg.jl, pull requests merged in 2022-04, with the labels that each got.

#3056 Before running the "test atomicity of write_env_usage" testset, make sure that the General registry has been installed
  test/pkg.jl
  test/utils.jl
Labels: test

#3065 Remove stdin forwarding from Pkg.test
  src/Operations.jl
Labels: backport pending 1.8

#3064 Minor compat edit mode error show fix
  src/API.jl
Labels: bugfix, backport pending 1.8

#3061 Ensure that test preferences are properly stacked
  .gitignore
  src/Operations.jl
  test/sandbox.jl
Labels: backport pending 1.8

#3070 CI: Re-enable testing on `i868-linux-gnu`
  .github/workflows/test.yml
Labels: CI
