Repository JuliaLang/Pkg.jl, pull requests merged in 2022-11, with the labels that each got.

#3250 Fix typos found by codespell
  src/API.jl
  src/Artifacts.jl
  src/GitTools.jl
  src/Operations.jl
  src/Resolve/Resolve.jl
  test/binaryplatforms.jl
  test/new.jl
  test/repl.jl
  test/test_packages/TestArguments/test/runtests.jl
Labels: merge me

#3252 add sandbox manual install for HistoricalStdlibVersions
  test/sandbox.jl
Labels: merge me

#3253 Check install for HistoricalStdlibVersions earlier
  test/runtests.jl
  test/sandbox.jl
Labels: merge me

#3254 Test suite: Try harder to `import HistoricalStdlibVersions`
  test/new.jl
  test/resolve.jl
  test/runtests.jl
Labels: merge me

#3258 Resolver refinement
  src/Resolve/Resolve.jl
  src/Resolve/graphtype.jl
  src/Resolve/maxsum.jl
  test/resolve.jl
  test/resolvedata.tar.gz
  test/resolvedata1.jl
  test/resolvedata2.jl
Labels: backport 1.8

#3262 Fix typo
  src/Pkg.jl
Labels: merge me

#3155 Clarify RegistrySpec docstring
  src/Pkg.jl
Labels: documentation, registries

#3156 slightly simplify API internals
  src/API.jl
Labels: Refactoring
