Repository JuliaLang/Pkg.jl, pull requests merged in 2022-08, with the labels that each got.

#3154 Clarify dependencies() docstring
  src/Pkg.jl
Labels: documentation

#3145 Remove dead code in Graph constructor
  src/Resolve/graphtype.jl
Labels: Refactoring, backport 1.6, backport 1.8

#3151 Add some tips to resolve conflict handling docs
  docs/src/environments.md
  docs/src/managing-packages.md
Labels: documentation, backport 1.8

#3168 Document that `.pkg/` hooks are only allowed to use `Base`, `Artifacts`, `Libdl`, and `TOML`
  docs/src/artifacts.md
Labels: documentation, artifacts

#3172 Mention the command 'compat'
  docs/src/compatibility.md
Labels: backport 1.8

#3176 Cleanup before exit after tests
  test/runtests.jl
Labels: merge me

#3179 fix API invalidations from Static.jl
  src/API.jl
Labels: backport 1.8

#3180 hopefully fix invalidations in API from AbstractFFTs
  src/API.jl
Labels: latency, backport 1.8

#3163 make tip about upgradability slightly more informative
  src/Operations.jl
  src/REPLMode/command_declarations.jl
  test/new.jl
Labels: backport 1.8
