Repository JuliaLang/Pkg.jl, pull requests merged in 2022-10, with the labels that each got.

#3213 Precompile: Fix touch on cache files to make sure latest is used first during load
  src/API.jl
Labels: backport 1.6, backport 1.8

#3217 refresh some of the documentation
  docs/make.jl
  docs/src/api.md
  docs/src/artifacts.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/faq.md
  docs/src/getting-started.md
  docs/src/glossary.md
  docs/src/index.md
  docs/src/managing-packages.md
  docs/src/registries.md
  docs/src/toml-files.md
  src/API.jl
  src/Artifacts.jl
  src/Pkg.jl
  src/REPLMode/command_declarations.jl
  src/Registry/Registry.jl
Labels: documentation

#3237 Fix reference to IOError on error path
  src/API.jl
Labels: backport 1.6, backport 1.8

#3096 Remove `Pkg.Types.STDLIBS_BY_VERSION` from Pkg, thus removing the need to constantly keep `STDLIBS_BY_VERSION` up to date
  .github/workflows/check_hsg.yml
  .github/workflows/run_hsg.yml
  ext/HistoricaStdlibGenerator/Manifest.toml
  ext/HistoricaStdlibGenerator/Project.toml
  ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl
  src/HistoricalStdlibs.jl
  src/Types.jl
  test/historical_stdlib_data.jl
  test/new.jl
  test/resolve.jl
Labels: merge me
