Repository JuliaLang/Pkg.jl, pull requests merged in 2022-01, with the labels that each got.

#2267 Stop printing "restricted by" if all versions are allowed.
  .gitignore
  src/Resolve/graphtype.jl
Labels: merge me

#2869 Add more examples to docs for `pkg> add`
  src/REPLMode/command_declarations.jl
  test/repl.jl
Labels: merge me

#2712 Docs: add comment for what `.` in `activate .` means
  docs/src/environments.md
Labels: merge me

#2293 Add subsection for offline mode
  docs/src/managing-packages.md
Labels: merge me

#2652 Tweak compatability documentation
  docs/src/compatibility.md
Labels: merge me

#2676 Docs: Mention automatic precompilation and link to more info
  src/Pkg.jl
  src/REPLMode/command_declarations.jl
Labels: merge me

#2901 Make sure that instantiate with platform works for the artifacts
  src/API.jl
  src/Operations.jl
  test/artifacts.jl
Labels: artifacts, backport pending 1.7

#2921 Set `__precompile__(false)` in the `ArtifactOverrideLoading` test package
  test/test_packages/ArtifactOverrideLoading/src/ArtifactOverrideLoading.jl
Labels: test

#2924 CI: don't skip intermediate builds on the `master` or `release-*` branches
  .github/workflows/test.yml
Labels: CI

#2936 README: add a little bit more context around the links to the Julia devdocs
  README.md
Labels: documentation, merge me

#2939 Make `free --all` not error if some are free already
  src/API.jl
  src/Operations.jl
  test/new.jl
Labels: backport pending 1.7

#2944 Fix manifest version check bug
  src/manifest.jl
  test/manifests.jl
Labels: backport pending 1.7

#2949 Make tests robust against Git's `init.defaultBranch` option being set, while still supporting Git 1.2.0+ and Git 2.0.0+
  test/subdir.jl
Labels: test, bugfix
