Repository JuliaLang/Pkg.jl, pull requests merged in 2023-10, with the labels that each got.

#3634 Make Pkg more resilient to reading older manifests where ex-stdlibs are listed
  src/Operations.jl
  src/Types.jl
  test/manifest/old/Manifest.toml
  test/manifest/old/Project.toml
  test/new.jl
Labels: backport 1.10

#3640 remove writing out explicit stdlib paths for the temporary testing manifest
  src/Operations.jl
Labels: backport 1.10

#3633 Make auto GC message use printpkgstyle
  src/Pkg.jl
Labels: backport 1.10

#3651 Fix algorithmic complexity of cycle detection
  src/API.jl
Labels: backport 1.9, precompile, backport 1.10

#3666 Pin registry for MetaGraph tests
  test/new.jl
Labels: backport 1.6, backport 1.9, backport 1.10

#3654 cache pidlock tweaks
  src/API.jl
Labels: backport 1.10

#3662 Precompilation workload: set `"JULIA_PKG_UNPACK_REGISTRY" => nothing`
  src/precompile.jl
Labels: bugfix

#3668 Precompilation workload: restore the original depot and load paths
  src/precompile.jl
Labels: bugfix

#3670 Stop manually propagate flags that julia_cmd will propagate
  src/Operations.jl
Labels: backport 1.10

#3660 Fix and update docs to Documenter 1
  docs/Project.toml
  docs/make.jl
  src/Pkg.jl
Labels: documentation

#3679 Precompile: Highlight when the lock is held by the same process
  src/API.jl
Labels: precompile, backport 1.10
