Repository JuliaLang/Pkg.jl, pull requests merged in 2023-11, with the labels that each got.

#3683 Don't clean test temp files
  Project.toml
  test/runtests.jl
  test/utils.jl
Labels: merge me

#3696 remove recompilation dependency check in Pkg.precompile
  src/API.jl
Labels: backport 1.9, precompile, backport 1.10

#3690 Move "Creating Packages" to Julia docs
  docs/generate.jl
  docs/make.jl
  docs/src/api.md
  docs/src/artifacts.md
  docs/src/basedocs.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/glossary.md
  docs/src/registries.md
  docs/src/toml-files.md
Labels: documentation

#3699 Use `startup=no` during `build` unless julia session explicitly set `startup=yes`
  src/Operations.jl
Labels: backport 1.10
