Repository JuliaLang/Pkg.jl, pull requests merged in 2023-04, with the labels that each got.

#3431 precompile: fix minor print bug
  src/API.jl
Labels: backport 1.8, backport 1.9

#3432 precompile: include extensions when packages are specified
  src/API.jl
  test/extensions.jl
Labels: backport 1.9

#3435 fix handling of relative paths in `bind_artifact!`
  src/Artifacts.jl
  test/artifacts.jl
Labels: artifacts, bugfix, backport 1.9

#3437 precompile: improve no match error messaging
  src/API.jl
  test/api.jl
Labels: backport 1.9
