Repository JuliaLang/Pkg.jl, pull requests merged in 2023-05, with the labels that each got.

#3457 fix color_string
  src/API.jl
Labels: bugfix, backport 1.9, precompile

#3451 update note on package extensions
  docs/src/creating-packages.md
Labels: backport 1.9

#3456 precompile: fix race in precompiling exts
  src/API.jl
Labels: backport 1.9, precompile

#3473 try_prompt_pkg_add: on "other" preselect the first non-default env
  src/REPLMode/REPLMode.jl
Labels: backport 1.9

#3467 Use correct threads specification for subprocess
  src/Operations.jl
Labels: backport 1.9

#3478 remove double backquote
  src/Pkg.jl
Labels: backport 1.9

#3480 [release-1.9] 1.9.1 Backports
  docs/src/creating-packages.md
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  src/REPLMode/REPLMode.jl
Labels: do not squash

#3485 Revert "Reland "precompile: fix race in precompiling exts (#3456)""
  src/API.jl
Labels: backport 1.9

#3493 Remove `VERSION` check for threadpools
  src/Operations.jl
Labels: backport 1.9

#3302 Clarify what "tiered" means
  src/Pkg.jl
  src/REPLMode/command_declarations.jl
Labels: documentation, backport 1.9
