Repository JuliaLang/Pkg.jl, pull requests merged in 2023-02, with the labels that each got.

#3331 precompile: show stderr warnings when process is interrupted
  src/API.jl
Labels: backport 1.9

#3353 fix `stale_cache` calculation
  src/API.jl
Labels: backport 1.9

#3359 fixup! #3353, recover `_is_stale!` logic
  src/API.jl
Labels: backport 1.9

#3373 no longer consider DelimitedFiles an stdlib even though it is stored in stdlib folder
  src/Types.jl
Labels: needs test, backport 1.9

#3382 Some improvements to documentation about creating packages
  docs/src/creating-packages.md
Labels: documentation

#3372 Various updates to extension documentation
  docs/src/creating-packages.md
Labels: documentation, backport 1.9

#3371 fixup jll versions that are supposed to stay fixed during e.g Pkg.add
  src/API.jl
  src/Operations.jl
  src/Pkg.jl
  test/new.jl
Labels: bugfix, backport 1.6, backport 1.9

#3384 Drop `select_platform()` tests
  test/binaryplatforms.jl
Labels: backport 1.9

#3349 Don't clear executable bits in `set_readonly()` on Windows
  src/Artifacts.jl
  src/utils.jl
  test/artifacts.jl
Labels: needs test
