Repository JuliaLang/Pkg.jl, pull requests merged in 2023-01, with the labels that each got.

#3051 Respect the IO for downloads in instantiate
  src/API.jl
Labels: backport 1.8, backport 1.9

#3295 fix precompiling list of packages with commas
  src/REPLMode/REPLMode.jl
  test/new.jl
Labels: backport 1.8, backport 1.9

#3306 Backport PR #3303 ("Respect manifest if provided in Project.toml") to Julia 1.9
  src/API.jl
  src/Operations.jl
  src/Types.jl
  test/project_manifest.jl
  test/runtests.jl
  test/test_packages/monorepo/Project.toml
  test/test_packages/monorepo/packages/B/Project.toml
  test/test_packages/monorepo/packages/B/src/B.jl
  test/test_packages/monorepo/packages/C/Project.toml
  test/test_packages/monorepo/packages/C/src/C.jl
  test/test_packages/monorepo/packages/C/test/runtests.jl
  test/test_packages/monorepo/packages/D/Project.toml
  test/test_packages/monorepo/packages/D/src/D.jl
  test/test_packages/monorepo/src/A.jl
  test/test_packages/monorepo/test/runtests.jl
Labels: release

#3309 add some type annotations to improve type stability
  src/GitTools.jl
  src/Types.jl
  src/manifest.jl
  src/project.jl
Labels: latency, backport 1.9

#3308 also check build ids when checking for staleness of precompile files
  src/API.jl
Labels: backport 1.9

#3311 Fix atomic test for pkgimages
  test/pkg.jl
Labels: backport 1.9

#3310 Backports release 1.9
  .github/workflows/test.yml
  src/API.jl
  src/GitTools.jl
  src/REPLMode/REPLMode.jl
  src/REPLMode/command_declarations.jl
  src/Types.jl
  src/manifest.jl
  src/project.jl
  test/pkg.jl
  test/repl.jl
Labels: release

#3325 more invalidation hunting
  src/Types.jl
Labels: backport 1.9

#3324 RFC: set `max_methods` to 1 in Pkg
  src/Pkg.jl
Labels: latency, backport 1.9

#3282 Docs: polish & expand weakdeps
  docs/src/creating-packages.md
Labels: backport 1.9

#3338 prevent passing stdout to git commands
  src/GitTools.jl
Labels: backport 1.6, backport 1.8, backport 1.9

#3334 precompile: add timing mode
  CHANGELOG.md
  src/API.jl
  src/Pkg.jl
  test/api.jl
Labels: backport 1.9
