Repository JuliaLang/Pkg.jl, pull requests merged in 2023-08, with the labels that each got.

#3565 Add debug info if repeated precompilation is hit in tests
  test/api.jl
Labels: merge me

#3561 precompile: try to prevent wrapping-caused mess during pretty printing
  src/API.jl
  src/MiniProgressBars.jl
Labels: precompile

#3572 precompile: also consider sysimage modules that activate extensions
  src/API.jl
Labels: backport 1.9, backport 1.10

#3536 precompile: pipe error messages during autoprecompilation to Main.err for easier inspection
  src/API.jl
  src/Types.jl
Labels: backport 1.9, backport 1.10

#3575 precompilation: `warnings` -> `output`
  src/API.jl
Labels: backport 1.9, backport 1.10

#3578 precompile: add retry message
  src/API.jl
Labels: backport 1.10

#3547 Remove mentions of “home project” in documentation and comments
  src/Pkg.jl
  src/REPLMode/command_declarations.jl
  test/api.jl
  test/new.jl
  test/repl.jl
Labels: backport 1.9, backport 1.10

#1800 Clarify "Providing global configuration options" in docs
  docs/src/glossary.md
Labels: documentation, backport 1.9, backport 1.10

#3584 precompile: stop swallowing internal errors
  src/API.jl
Labels: backport 1.9, precompile, backport 1.10

#3573 precompilation: capture stdout as well as stderr
  src/API.jl
Labels: precompile, backport 1.10

#2673 Give examples of using `julia_args`, `test_args`
  src/Pkg.jl
Labels: documentation, backport 1.9, backport 1.10, forget me not

#3585 fix inference of PackageSpec constructor in presence of imprecise input types
  src/Types.jl
  test/misc.jl
Labels: backport 1.9, backport 1.10

#3582 precompile: if a single package is requested, show output live
  src/API.jl
Labels: precompile, backport 1.10

#3579 Update manifest entry of project for non-local manifests
  src/Operations.jl
  test/project_manifest.jl
Labels: backport 1.9, backport 1.10

#3591 Don't mutate project.deps during project write
  src/project.jl
  test/test_packages/ExtensionExamples/HasDepWithExtensions.jl/Manifest.toml
  test/test_packages/ExtensionExamples/HasDepWithExtensions.jl/Project.toml
  test/test_packages/ExtensionExamples/HasDepWithExtensions.jl/src/HasDepWithExtensions.jl
  test/test_packages/ExtensionExamples/HasDepWithExtensions.jl/test/runtests.jl
  test/test_packages/ExtensionExamples/HasExtensions.jl/Manifest.toml
  test/test_packages/ExtensionExamples/HasExtensions.jl/Project.toml
  test/test_packages/ExtensionExamples/HasExtensions.jl/ext/IndirectArraysExt.jl
  test/test_packages/ExtensionExamples/HasExtensions.jl/src/HasExtensions.jl
  test/test_packages/ExtensionExamples/HasExtensions.jl/test/runtests.jl
Labels: backport 1.9, backport 1.10

#3597 Fix lacking `subdir` information when altering packages
  src/Types.jl
  test/subdir.jl
Labels: backport 1.10

#3526 Throw an error if the current Julia version (`Base.VERSION`) is incompatible with the `[compat]` entry for `julia` in the `Project.toml` file
  CHANGELOG.md
  src/Operations.jl
  test/api.jl
  test/test_packages/FarFuture/Project.toml
  test/test_packages/FarFuture/src/FarFuture.jl
  test/test_packages/FarPast/Project.toml
  test/test_packages/FarPast/src/FarPast.jl
Labels: needs changelog, feature

#3602 Test suite: activate a temp project if we need to install HistoricalStdlibVersions during the test suite
  test/runtests.jl
Labels: test, bugfix, backport 1.10

#3603 precompile: show ext parent in output report
  src/API.jl
Labels: precompile, backport 1.10

#3576 status: expand 2 symbol upgrade note to highlight *may* be upgradable
  src/Operations.jl
Labels: backport 1.9, backport 1.10

#3574 Tweak test dep docs
  docs/src/creating-packages.md
Labels: backport 1.10
