Repository JuliaLang/Pkg.jl, pull requests merged in 2023-07, with the labels that each got.

#3519 precompile: respect and report cache pidlocking
  src/API.jl
  test/api.jl
Labels: needs changelog, precompile

#3276 try improve the merging of sandbox manifest and parent manifest
  src/Operations.jl
Labels: merge me

#3528 Clarify error with project missing attributes
  src/API.jl
Labels: merge me

#3510 Note the exception to SymVer for leading zeros again
  docs/src/compatibility.md
Labels: documentation

#3538 handle git cli errors as pkgerrors
  src/GitTools.jl
  test/new.jl
Labels: backport 1.9, backport 1.10
