Repository JuliaLang/Pkg.jl, pull requests merged in 2024-10, with the labels that each got.

#4054 REPLExt: run repl hint generation for modeswitch chars when not switching
  ext/REPLExt/REPLExt.jl
Labels: REPL, backport 1.11

#4053 REPLExt: use Base.isaccessibledir rather than isdir in completions
  ext/REPLExt/completions.jl
Labels: backport 1.11

#4057 fix Base.unreference_module call
  test/artifacts.jl
Labels: merge me

#4062 strip out tree_hash for stdlibs that have have been freed in newer julia versions
  src/Operations.jl
Labels: backport 1.10, backport 1.11
