Repository JuliaLang/Pkg.jl, pull requests merged in 2024-11, with the labels that each got.

#4067 REPLExt: check for compliant repl mode during repl init
  ext/REPLExt/REPLExt.jl
Labels: merge me, backport 1.11

#4080 Actually switch to "Resolving Deltas"
  src/GitTools.jl
Labels: backport 1.10, backport 1.11

#4093 [backports-release-1.10] Backport julia/#55910 and julia/#56621
  src/API.jl
Labels: do not squash
