Repository JuliaLang/Pkg.jl, pull requests merged in 2024-06, with the labels that each got.

#3910 Precompile the pkg tab completion hint
  ext/REPLExt/precompile.jl
Labels: merge me

#3913 abort querying more packages for hint auto complete
  ext/REPLExt/REPLExt.jl
  ext/REPLExt/completions.jl
  src/REPLMode/command_declarations.jl
Labels: backport-1.11

#3887 Add version validation during resolve's graph analysis
  src/API.jl
  src/Resolve/Resolve.jl
  src/Resolve/graphtype.jl
  src/Resolve/maxsum.jl
  src/Versions.jl
  test/resolve.jl
  test/resolve_utils.jl
  test/resolvedata.tar.gz
Labels: do not squash

#3921 use the correct TOML.Parser coupled to Base.TOMLCache
  src/Registry/registry_instance.jl
  src/Types.jl
Labels: backport-1.11

#3930 Fix HistoricalStdlibVersions install to version
  test/runtests.jl
Labels: merge me, backport 1.10, backport 1.11
