Repository JuliaLang/Pkg.jl, pull requests merged in 2024-07, with the labels that each got.

#3934 rm `empty!` on `install_packages_hooks`
  ext/REPLExt/REPLExt.jl
Labels: backport 1.11

#3894 catch if the active project is erroneously set to a manifest file
  src/Types.jl
Labels: backport 1.10, backport 1.11

#3790 if re-resolve is needed instead run update and show diff
  src/Operations.jl
Labels: merge me

#3932 Don't retry artifact downloads on `SystemError`, like `no space left on device`
  src/PlatformEngines.jl
Labels: artifacts, backport 1.10, backport 1.11

#3903 Add some documentation describing how to interpret the symbols shown during recompilation
  docs/src/environments.md
Labels: merge me, backport 1.10, backport 1.11

#3945 Mark API public
  src/Pkg.jl
  src/Registry/Registry.jl
Labels: backport 1.11

#3951 fix artifact printing quiet rule
  src/Operations.jl
  src/Pkg.jl
Labels: backport 1.11

#3957 Pkg.test: document that coverage can be a string
  src/Pkg.jl
Labels: backport 1.10, backport 1.11

#3851 fix not hardcoding "Project.toml" when fixing up extensions in manifest
  src/Operations.jl
  src/Types.jl
Labels: backport 1.10, backport 1.11

#3967 check `project_file` isa String
  src/Operations.jl
Labels: backport 1.10, backport 1.11

#3968 fix suggestions threshold for printing
  src/Types.jl
  src/fuzzysorting.jl
Labels: backport 1.11
