Repository JuliaLang/Pkg.jl, pull requests merged in 2024-03, with the labels that each got.

#3835 re-enable Pkg precompilation
  src/precompile.jl
Labels: backport-1.11

#3840 test env precompile: move threads assignment after precompilation
  src/Operations.jl
Labels: sandbox, precompile, backport-1.11

#3838 precompile: update kwargs
  src/API.jl
  src/Operations.jl
Labels: precompile

#3858 remove unused PkgPrecompileError type
  src/Types.jl
Labels: backport-1.11
