Repository JuliaLang/Pkg.jl, pull requests merged in 2025-06, with the labels that each got.

#4261 Explain that no registry is installed when no registry is installed
  src/Operations.jl
  test/pkg.jl
Labels: error handling, backport 1.12

#4270 feat(errors): Improve error message for incorrect package UUID
  src/Operations.jl
  test/new.jl
  test/pkg.jl
Labels: backport 1.10, backport 1.12

#4254 prompt for confirmation before removing compat entry
  src/API.jl
Labels: backport 1.10, backport 1.11, backport 1.12

#4271 fix what project file to look at when package without path but with a subdir is devved by name
  src/Types.jl
  test/subdir.jl
Labels: backport 1.12

#4276 copy the app project instead of wrapping it
  src/Apps/Apps.jl
Labels: backport 1.12
