Repository JuliaLang/Pkg.jl, pull requests merged in 2025-02, with the labels that each got.

#4148 reset caching of STDLIBs reading after precompilation is done
  src/Pkg.jl
  src/Types.jl
Labels: backport 1.11, backport 1.12

#4150 Add Aqua tests. Add missing compats
  Project.toml
  test/Project.toml
  test/aqua.jl
  test/runtests.jl
Labels: backport 1.12

#4156 Add more tests for BinaryBuilder usage
  test/historical_stdlib_version.jl
Labels: binarybuilder

#4141 Changed Pkg.test to prioritise julia_args --threads over current process threads
  src/Operations.jl
  test/new.jl
  test/test_packages/.gitignore
  test/test_packages/TestThreads/Project.toml
  test/test_packages/TestThreads/src/TestThreads.jl
  test/test_packages/TestThreads/test/runtests.jl
Labels: backport 1.11, backport 1.12

#4177 Update docs for versioned manifest
  docs/src/toml-files.md
Labels: backport 1.10, backport 1.11
