Repository JuliaLang/Pkg.jl, pull requests merged in 2025-07, with the labels that each got.

#4279 Various improvements to docs and docstrings
  docs/make.jl
  docs/src/api.md
  docs/src/apps.md
  docs/src/artifacts.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/getting-started.md
  docs/src/glossary.md
  docs/src/managing-packages.md
  docs/src/registries.md
  docs/src/toml-files.md
  src/Pkg.jl
  src/REPLMode/command_declarations.jl
Labels: backport 1.12

#4229 collect paths for input packages that are in a workspace
  src/API.jl
  test/test_packages/WorkspacePathResolution/Project.toml
  test/test_packages/WorkspacePathResolution/SubProjectA/Project.toml
  test/test_packages/WorkspacePathResolution/SubProjectA/src/SubProjectA.jl
  test/test_packages/WorkspacePathResolution/SubProjectB/Project.toml
  test/test_packages/WorkspacePathResolution/SubProjectB/src/SubProjectB.jl
  test/workspaces.jl
Labels: backport 1.12

#4096 Clarify guidelines
  docs/src/creating-packages.md
  docs/src/toml-files.md
Labels: merge me

#4162 Apps: Switch to more portable shell shebang
  src/Apps/Apps.jl
Labels: merge me

#3761 Show preserve strategy in resolve
  src/Operations.jl
Labels: merge me

#3173 update the Pkg.test docs
  src/Pkg.jl
Labels: merge me

#3525 `Pkg.test`: add more detail to the "Could not use exact versions of packages in manifest, re-resolving" message
  src/Operations.jl
Labels: merge me

#3625 Update development instructions
  README.md
Labels: merge me

#3106 propagate `include_lazy` through `download_artifacts`
  src/Operations.jl
Labels: merge me, backport 1.12

#3122 warn & strip on accidental leading `]`
  src/REPLMode/REPLMode.jl
  test/repl.jl
Labels: merge me

#3613 Note disabling autoprecompilation in Pkg.instantiate docstring
  src/Pkg.jl
Labels: merge me

#4287 Enhance fuzzy matching algorithm with multi-factor scoring
  CHANGELOG.md
  src/Types.jl
  src/fuzzysorting.jl
  test/new.jl
Labels: backport 1.12

#2330 Change refs/* to refs/heads/* to speed up repo cloning w/ many branches
  src/Types.jl
Labels: merge me, backport 1.12

#4302 improve error message info for bad compat entries
  src/precompile.jl
  src/project.jl
Labels: error handling

#3344 add support for `Pkg.add(path="/path/to/git-submodule.jl")` directly.
  src/Types.jl
Labels: merge me

#4303 Add more info when package is missing
  src/Operations.jl
  test/pkg.jl
Labels: error handling

#4299 Fix parsing to better handle branch/tag/subdir specifiers in complex URLs and paths
  src/REPLMode/REPLMode.jl
  src/REPLMode/argument_parsers.jl
  src/utils.jl
  test/new.jl
  test/repl.jl
  test/subdir.jl
Labels: bugfix, backport 1.12

#4312 fix `status --diff` to work when package is in a non-root path
  src/Operations.jl
  src/utils.jl
  test/new.jl
Labels: backport 1.12

#3266 add `pkg> compat --current` mode
  CHANGELOG.md
  ext/REPLExt/REPLExt.jl
  ext/REPLExt/compat.jl
  src/API.jl
  src/REPLMode/command_declarations.jl
  test/new.jl
Labels: merge me, forget me not, compat bounds

#4315 Fix typos and inconsistencies in documentation
  docs/src/artifacts.md
  docs/src/basedocs.md
  docs/src/compatibility.md
  docs/src/creating-packages.md
  docs/src/environments.md
  docs/src/getting-started.md
  docs/src/glossary.md
  docs/src/managing-packages.md
  docs/src/toml-files.md
Labels: documentation

#4316 Fix lack of color in CI and don't warn about loaded packages in test Pkg.precompile.
  src/API.jl
  src/Operations.jl
Labels: backport 1.10, backport 1.11, backport 1.12

#4325 fix parsing of multiple packages with modifiers on some of them
  src/REPLMode/argument_parsers.jl
  test/new.jl
Labels: backport 1.12

#4335 Error if the stdlib version requested mismatches current version
  src/Operations.jl
  test/api.jl
Labels: binarybuilder, backport 1.10, backport 1.11, backport 1.12
